# Production Docker Compose Override
# Use this file for production-specific configurations
# Run with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  database:
    # Remove port exposure in production for security
    ports: []
    environment:
      # Production database settings
      POSTGRES_SHARED_PRELOAD_LIBRARIES: 'pg_stat_statements'
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  backend:
    environment:
      NODE_ENV: production
      # Disable debug logging in production
      LOG_LEVEL: warn
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        max_attempts: 3

  frontend:
    environment:
      # Production-specific frontend settings
      NGINX_WORKER_PROCESSES: auto
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
